---
- name: Preparing Workstation
  hosts: localhost
  connection: local
  tasks:

    - name: Installing Linux Apps
      become: true
      apt:
        name: '{{ item }}'
        install_recommends: yes
        state: present
      loop:
          - vim
          - tcl
          - dkms
          - openjdk-11-jdk-headless
          - xclip
          - curl
          - wget
          - apt-transport-https
          - ca-certificates
          - python3-pip
          - make
          - bash-completion
          - pdsh
          - build-essential
          - binutils
          - gcc
          - cmake
          - openssh-server
          - r-base-core
          - net-tools 
          - perl
          - gnupg
          - gnupg-agent
          - lsb-release
          - python3-venv
          - libpq-dev
          - python3-dev
          - python3-wheel
          - pandoc
          - texlive-xetex 
          - texlive-fonts-recommended
          - texlive-plain-generic
          - maven
          - libssl-dev
          - zlib1g-dev
          - libbz2-dev
          - libreadline-dev
          - libsqlite3-dev
          - llvm
          - libncursesw5-dev
          - xz-utils
          - tk-dev
          - libxml2-dev 
          - libxmlsec1-dev
          - libffi-dev
          - liblzma-dev

    - name: Installing AWS CLI via pip3
      become: true
      pip:
        name: awscli
        state: present

    - name: Installing Apps Pip3
      become: true
      pip:
        name: jupyterlab, findspark, pandas, numpy, koalas, plotly, jupyter, grpcio, protobuf, wheel, spylon-kernel, jill
        state: present

    - block:
      - name: Install Terraform
        become: true
        apt_key:
          url: 'https://apt.releases.hashicorp.com/gpg'
          state: present
      - name: Install Terraform Repository
        become: true
        apt_repository:
          repo: 'deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main'
          state: present
          filename: terraform
      - name: Install Terraform
        become: true
        apt:
          name: terraform
      
    - block:
      - name: Install Google Cloud SDK Key
        become: true
        apt_key:
          url: 'https://packages.cloud.google.com/apt/doc/apt-key.gpg'
          state: present
      - name: Install Google Cloud SDK Repository
        become: true
        apt_repository:
          repo: 'deb [arch=amd64] https://packages.cloud.google.com/apt cloud-sdk main'
          state: present
          filename: google-cloud-sdk
      - name: Install Google Cloud SDK
        become: true
        apt:
          name: google-cloud-sdk

    - block: 
      - name: Install Docker Key
        become: true
        apt_key:
          url: 'https://download.docker.com/linux/ubuntu/gpg'
          state: present
      - name: Install Docker Repository
        become: true
        apt_repository:
          repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
          state: present
          filename: docker-ce
      - name: Installing Docker Apps
        become: true
        apt:
          name: '{{ item }}'
          install_recommends: yes
          state: present
        loop:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
      - name: Adding existing user to group Docker
        become: true
        user: 
          name: '{{ ansible_user_id }}'
          groups: docker 
          append: yes
      - name: Install Docker-Compose
        become: true
        get_url:
          # url: 'https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64'
          url: 'https://github.com/docker/compose/releases/download/v2.11.2/docker-compose-linux-x86_64'
          dest: '/usr/local/bin/docker-compose'
          mode: 755
      - name: Install Docker Machine Bash Completion
        become: true
        get_url:
          url: 'https://raw.githubusercontent.com/docker/machine/v0.16.0/contrib/completion/bash/docker-machine.bash'
          dest: '/etc/bash_completion.d/docker-machine'
      - name: Install Docker-Compose Bash Completion
        become: true
        get_url:
          url: 'https://raw.githubusercontent.com/docker/compose/1.26.2/contrib/completion/bash/docker-compose'
          dest: '/etc/bash_completion.d/docker-compose'